<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_materi</name>
   <tag></tag>
   <elementGuidId>0efdaa48-acb8-4f0a-a8eb-876967c1dcf9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='kegiatan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;kegiatan&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>select[name=&quot;kegiatan&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5fc610ce-6c7c-4559-a9be-57e645533821</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>cb9ed9e5-386f-4551-b0eb-7cb864312361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>-Select-</value>
      <webElementGuid>d726883d-17fe-47cf-bdbe-0f67a5b8def3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kegiatan</value>
      <webElementGuid>3b12fa6a-587c-40f2-aa6a-39f54d2a2c3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--Searching MateriBelajar MateriBuat Laporan/Presentasi/ProposalLayoutInterview/Tinjauan LapanganIdentifikasi DokumenOlah Data (Excel)Input DataBuat KuosionerBuat Lembar KerjaTrainingTestingProgrammingInstall Alat/SistemPresentasiMeeting/Rapat</value>
      <webElementGuid>e876ab65-d520-47d6-be74-5e1228d2152c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;c-app c-default-layout&quot;]/div[@class=&quot;c-wrapper&quot;]/div[@class=&quot;c-body&quot;]/main[@class=&quot;c-main&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;fade show&quot;]/div[@class=&quot;container-mains&quot;]/div[4]/div[@class=&quot;modal overflow-auto fade show d-block&quot;]/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content&quot;]/form[1]/div[@class=&quot;mb-4 card-body&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;row form-group my-0 mx-2&quot;]/div[@class=&quot;col-8&quot;]/div[@class=&quot;form-group&quot;]/select[@class=&quot;form-control&quot;]</value>
      <webElementGuid>f5e340c0-7935-4bc0-85c8-875303201637</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='kegiatan']</value>
      <webElementGuid>f055b3f3-6dbe-48f0-b6a9-774b0e71f2bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/main/div/div/div/div[4]/div/div/div/form/div/div[2]/div[8]/div[2]/div/select</value>
      <webElementGuid>225acd19-141f-48e4-b71f-4b4fcd72f776</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kegiatan'])[1]/following::select[1]</value>
      <webElementGuid>6f232a01-f3da-4522-a905-9ebebc0575af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Use Case'])[1]/following::select[1]</value>
      <webElementGuid>3d1cd0c2-8750-4ff9-aa44-89e43e980476</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hasil'])[1]/preceding::select[1]</value>
      <webElementGuid>1c1e9be4-c212-47bb-92ca-9009e477dce0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Line of Code'])[1]/preceding::select[1]</value>
      <webElementGuid>2c87d635-ccff-495b-ae56-fd4d42e51c6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/div/select</value>
      <webElementGuid>6ddefd98-bce0-494b-976f-7517a2d72be5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@placeholder = '-Select-' and @name = 'kegiatan' and (text() = '--Select--Searching MateriBelajar MateriBuat Laporan/Presentasi/ProposalLayoutInterview/Tinjauan LapanganIdentifikasi DokumenOlah Data (Excel)Input DataBuat KuosionerBuat Lembar KerjaTrainingTestingProgrammingInstall Alat/SistemPresentasiMeeting/Rapat' or . = '--Select--Searching MateriBelajar MateriBuat Laporan/Presentasi/ProposalLayoutInterview/Tinjauan LapanganIdentifikasi DokumenOlah Data (Excel)Input DataBuat KuosionerBuat Lembar KerjaTrainingTestingProgrammingInstall Alat/SistemPresentasiMeeting/Rapat')]</value>
      <webElementGuid>a8314c36-76c7-41d2-8e0d-2ad94f4f0834</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
